environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g bower phantomjs-prebuilt
  - yarn
  - bower install

cache:
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\Yarn'
  - node_modules

test_script:
  - cmd: yarn run test-win

build: off
